### ISSUE TITLE
Release version 1.0 

### ISSUE THREAD

**Issue by DLMR** [vgno/roc-deprecated#23]
To make the CLI more flexible and powerful we should refactor it to be more dynamic and configurable. One way to do this is to move the extensions specific commands to the extensions. Other than making it more flexible to work with we get the added benefit that we do not need to install anything globally to build and run individual projects since they can expose their own commands from themselves. These commands should however be exposed from the main Roc CLI as well when used.

To make this possible the extensions need to add something like the following to their exposed API.

``` js
// Takes in a process.argv argument and is responsible to run the commands
runCommand(arguments)

// Prints help information for a specific command or if empty the general commands 
// possible. If a command is given and that command want to parse command options 
// to roc configuration options roc-config can be used to do that
getHelp(command)

// Just returns the version of the extension
getVersion()
```

The extension is responsible for managing extending other extensions and generally the recommended way will be for the top most extension to handle everything it can handle, possibly override some commands and then after that calling the parent for it. This means if both the child and the parent has a `build` command the client will manage that and if it needs something from the parent it will use direct API:s to access that.

This could be implemented in a similar way to how configurations are handled today, meaning that the CLI commands themselves can be part of the `roc.config.js` file in the extensions. This would create a simple and straightforward way to manage commands on an application level. What do you think @andreasrs?

---

__Needed to release v1.0__

* [ ] Move extension based commands to the extensions, leaving only general commands in this repo. Also make the described approach above work.
* [ ] Reimplement the update command and the version checking.
* [ ] Implement more tests to get a better coverage and make updates and changes in the future easier.
* [ ] Go over the documentation and make sure that it's up to date and relevant.

Anything to add here @andreasrs?

**Comment by andreasrs** [comment]
+1
I agree, we discussed this before and I agree it should be in place before we make a stable release.

On another note each extension layer now provides the following:
- Building
- Code used by Roc apps at runtime (bundled into their app)
- CLI runtimes (discussed in this issue)

There are advantages and disadvantages to splitting this up further and I'm not 100% sure we want to. But it should be discussed, we'll have to keep a clear separation of concerns as the project evolves.

**Comment by DLMR** [comment]
I have thought about the same things here and it would be natural to split the extensions into at least the code used for building and the code used for the apps. This would make it easy to have another base inside the applications but still uses the same build system without needing to duplicate any code between projects. This will make even more sense when Roc grows and more types of targets are added, creating a `roc-core` would be something natural.

However that split is something that I think we should wait until after v1.0.

@andreasrs What do you think about the suggested API above, and if we should use the configuration files to do this to some extent.
